---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nginx
  namespace: test
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: nginx
  chart:
    git: https://github.com/varunvijay91/kube-helm-flux.git
    ref: master
    path: get_started/charts/nginx