---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nginx
  namespace: test
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: nginx
  chart:
    git: ssh://git@github.com:varunvijay91/kube-helm-flux.git
    ref: master
    path: charts/nginx